###################################
### GENERAL, HEADER & META TAGS ###
###################################

logo: ""                                                                        # Logo for your blog. Leave empty if you don't have one
blog_name: "Oliver's blog"                                                              # Give your blog a meanungful name.
title: "The easies way to learn english"             # Give your blog a meaningful title. This is used for the HTML title attribute
title_short: "blog"                                                            # Place the name of your blog or a short title here
short_description: "The easies way to learn english"         # Short description for your blog
meta_description: "sad as das asd asd as dsa dsadsad asdasd"  # meta description tag
meta_author: "Oliver Powell"                                                         # meta tag for author
keywords: "blog"                                          # your keywords
og_logo: "#"   # OpenGraph logo
geo_position: "50.00"                                                     # Geo tags for position and address
geo_address: "test test"                                              # Geo tags for position and address


##############
### SOCIAL ###
##############

# Your Twitter and Google+ profile URL
# Leave empty if you don't want to display inside the footer
twitter_url: '#'
gplus_url: '#'


#################
### ATOM FEED ###
#################

feed_title: "Learning made easyer"        # give your feed a title
feed_logo: "#" # full URL to the feed logo. Aspect ratio should be 2:1
feed_favicon: "#" # full URL to the favicon. Aspect ratio should be 1:1


#####################
### APP SPECIFICS ###
#####################

refresh_sitemap: false

hero_images: ["lines_default_01.png", "lines_default_02.png", "lines_default_03.png"]

articles_per_page: 10 # Pagination: How many articles should be desplayed per page?

# Your apps secret token. Generate a new one with 'rake secret' and paste it below
secret_token: "afa4a436180a2febe9b814c6a57b6f3ad298aa82ce0ab4c9e8238713764b665e978f9fad8146587b6cf4a518de4a8f0eac1156cf43a778548e0082629d099fef"

# Carrierwave uploader
storage: :file # or "aws" if using carrierwave-aws or "ftp" of using carrierwave-ftp

# Environment dependent configuration. Place your URLs here
development:
  host: "cvktne7b4wbj4ks1.chr7pe7iynqr.eu-west-1.rds.amazonaws.com"
  from_email: 'noreply@example.com'
test:
  host: "cvktne7b4wbj4ks1.chr7pe7iynqr.eu-west-1.rds.amazonaws.com"
  from_email: 'noreply@example.com'
production:
  host: "cvktne7b4wbj4ks1.chr7pe7iynqr.eu-west-1.rds.amazonaws.com"
  from_email: <%= ENV["MAILER_EMAIL"] %>
