# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70ca07475cc2bc5d67d7c49e2559d8090188f06c44088f1a17b07034dcd20c86f736b70433daae2ddeaea61d6c7b66b65fcb1064c2af3422d3374859ebb8add5

test:
  secret_key_base: fd7375e919d891a6b6026802fa4975d09801e20f25c596412730ef971f0fb71b064b084bd5a3a92374838cded3d3e1a2f3d607e5c8b6f3222dc23824ad5e5dce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 'blipblapblup'